---
# Dataset specifications --------------------------------------

data_dir: "/content/drive/.shortcut-targets-by-id/1RJrfHJH4cf0Lh3tIncNUardvP0Vi1GQ9/Generative_Models/data" # Location where data is stored
train_data: "train_sequences.tsv" # Dataset to use for training
val_data: "val_sequences.tsv" # Dataset to use for validation

# Training hyperparams --------------------------------------

num_classes: 23 # Number of different tokens (20 aa + pad + start + end)
epochs: 1500 # Number of steps to train.
batch_size: 64 # Number of elements in input batch
d_model: 512 # Maximum sequence lenght of the output protein, i.e. dimension of the model
lr: 0.01 # Learning rate